name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/myapp
            TAG=${{ github.event.workflow_run.head_sha }}

            # Install dependencies
            sudo apt-get update -y
            sudo apt-get install -y docker.io apache2

            # Run container on port 8080
            sudo docker rm -f myapp || true
            sudo docker pull $IMAGE:$TAG
            sudo docker run -d --name myapp -p 8080:80 $IMAGE:$TAG

            # Configure Apache as reverse proxy
            sudo a2enmod proxy
            sudo a2enmod proxy_http
            sudo bash -c 'cat > /etc/apache2/sites-available/000-default.conf <<EOF
            <VirtualHost *:80>
                ServerAdmin webmaster@localhost
                ProxyPass / http://127.0.0.1:8080/
                ProxyPassReverse / http://127.0.0.1:8080/
            </VirtualHost>
EOF'

            # Restart Apache
            sudo systemctl restart apache2
